[package]
name = "rooster_ast"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1"
once_cell = "1"
rooster_types = {path = "../rooster_types"}
tokio = {version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync"]}
