[package]
name = "nacre_cache"
version = "0.1.0"
edition = "2024"

[dependencies]
once_cell = "1"
tokio = {version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync"]}

[lints.clippy]
too_many_lines = "warn"
