[package]
name = "nacre_ast"
version = "0.1.0"
edition = "2021"

[dependencies]
async-recursion = "1"
once_cell = "1"
nacre_types = {path = "../nacre_types"}
tokio = {version = "1", features = ["fs", "io-util", "macros", "rt-multi-thread", "sync"]}

[lints.clippy]
too_many_lines = "warn"
